### PR TITLE
Add support for test methods

### LINKED ISSUE #5: Support for test methods
Currently asyncio doesn't support test methods (see #4):

```python
class Test:
    @pytest.mark.asyncio
    def test_some_asyncio_code(self):
        res = yield from library.do_something()
        assert b'expected result' == res
```

### PR DESCRIPTION
**Pull request by nicoddemus**
- Inspired on the default implementation for pytest_pyfunc_call for normal test functions
- Refactor pytest_pyfunc_call to remove duplication

fixes #5

(BTW @Tinche, hope you don't mind me creating a branch in this repository instead of on a fork... let me know if you prefer the latter).

### CODE REVIEW

**Comment by GMLudo** [comment]
@nicoddemus or @Tinche: Is should be possible to configure coverage to don't have a comment message each time? coreralls is already present in the check list, with Travis-CI.

**Comment by nicoddemus** [comment]
@GMLudo I'm not sure... I also find them a little annoying to be honest, but they are useful.

Just updated the PR fixing the missing coverage lines. On thing I thought strange was that the missing coverage lines were almost the entire `pytest_pyfunc_call` function... 

I just commented that function out locally and the tests still pass... :flushed:

**Comment by GMLudo** [comment]
@nicoddemus, yes it's really useful, like Travis-CI, nevertheless, at least to me, the checks in pull requests is less annoying that a new comment.

**Comment by Tinche** [comment]
@nicoddemus Looks great to me! Thanks for dealing with this so quickly. As for branches/repos, just do what you feel most comfortable with.

@GMLudo I've disabled coveralls comments in pull requests. I have to admit I wasn't even aware of the 'Show all checks' thingy until now, pretty nifty!

**Pull request merged**
