### PR TITLE
Test on Python 3.8, drop 3.3 and 3.4

### LINKED ISSUE #129: Python 3.8 breakage
On Python 3.8 the test summary is

`========= 6 failed, 28 passed, 1 skipped, 1 xfailed, 2 error in 1.76s ==========`

All failures and errors are the same:

Example error
```py
[   61s] ==================================== ERRORS ====================================
[   61s] ___________________ ERROR at setup of test_dependent_fixture ___________________
[   61s] tests/conftest.py:24: in dependent_fixture
[   61s]     event_loop.run_until_complete(just_a_sleep())
[   61s] /usr/lib/python3.8/asyncio/base_events.py:608: in run_until_complete
[   61s]     return future.result()
[   61s] tests/conftest.py:20: in just_a_sleep
[   61s]     await asyncio.sleep(0.1, loop=event_loop)
[   61s] /usr/lib/python3.8/asyncio/tasks.py:639: in sleep
[   61s]     warnings.warn("The loop argument is deprecated since Python 3.8, "
[   61s] E   DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
```

Example failure
```py
[   61s] ==================================== ERRORS ====================================
[   61s] ___________________ ERROR at setup of test_dependent_fixture ___________________
[   61s] tests/conftest.py:24: in dependent_fixture
[   61s]     event_loop.run_until_complete(just_a_sleep())
[   61s] /usr/lib/python3.8/asyncio/base_events.py:608: in run_until_complete
[   61s]     return future.result()
[   61s] tests/conftest.py:20: in just_a_sleep
[   61s]     await asyncio.sleep(0.1, loop=event_loop)
[   61s] /usr/lib/python3.8/asyncio/tasks.py:639: in sleep
[   61s]     warnings.warn("The loop argument is deprecated since Python 3.8, "
[   61s] E   DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
```

### PR DESCRIPTION
**Pull request by asvetlov**
Fixes #129

@Tinche please review

### CODE REVIEW

**Comment by michael-k** [comment]
Can you add the Python 3.8 classifier to setup.py?

Would be nice to see a release with Python 3.8 support.

**Comment by asvetlov** [comment]
Done

**Comment by L1ghtn1ng** [comment]
@Tinche Can you please merge this in so it can support py3.8? Also when is a release going to be done(tagged) with py3.8 support?

**Comment by blueyed** [comment]
:+1: 
Missed this when creating https://github.com/pytest-dev/pytest-asyncio/pull/134 - which still makes up for a cleaner .travis.yml though.  Please consider adopting it, or we can otherwise do it (#134) later.

**Comment by blueyed** [comment]
I think it would be nicer to have this rebased on master, so that e.g. https://github.com/pytest-dev/pytest-asyncio/pull/133/commits/0f86f798d0ca35ca0e16365414cebd030f2984ee was not necessary (a fixup after master was merged into it).

**Comment by Tinche** [comment]
I plan on pulling this in before the next release, so soon! Could I ask that merge conflicts are fixed please @asvetlov

**Comment by fulaphex** [comment]
@Tinche there are no more conflicts, could you merge it to unblock the release?

**Comment by Tinche** [comment]
> @Tinche there are no more conflicts, could you merge it to unblock the release?

There are still conflicts :)

**Comment by fulaphex** [comment]
I might be missing something, but here is how it looks on my end:
image
That's why I pinged you

**Comment by simonfagerholm** [comment]
@fulaphex I'm guessing that was the state at the time of the last push, not current state

**Comment by L1ghtn1ng** [comment]
Even for me it is saying there are no conflicts

**Comment by Tinche** [comment]
Screenshot 2020-04-08 at 19 02 16

Huh, weird.

**Comment by michael-k** [comment]
I tried to rebase this branch on master and ended in rebase hell, but squash merging it worked fine.  I've created a PR #152 which is effectively a rebase-and-squash of this PR (including proper attribution).

Hope this helps to unblock the next release.

**Comment by Tinche** [comment]
Superceded by https://github.com/pytest-dev/pytest-asyncio/pull/152.

**Pull request closed without merging**
