### PR TITLE
Alternative policies support

### PR DESCRIPTION
**Pull request by Tinche**
Introduces code for handling custom event loop policies and tests for it.

Apologies for reformatting noise, I'm using black now.

### CODE REVIEW

**Comment by Tinche** [comment]
The tests are failing atm because in the test scenario and in the toy project I've created to test this the event_loop fixture gets executed before the `event_loop_policy` fixture for the first test only. This could be because we inject the event_loop fixture into the list of fixtures as the first element. So maybe the logic there could be improved.

**Comment by Tinche** [comment]
One fix is to override the `event_loop` fixture to depend on your `event_loop_policy` fixture explicitly:

```
@pytest.fixture(autouse=True, scope="session")
def event_loop_policy():
    asyncio.set_event_loop_policy(CustomSelectorLoopPolicy())
    yield
    asyncio.set_event_loop_policy(None)


@pytest.fixture()
def event_loop(event_loop_policy):
    return asyncio.new_event_loop()
```
This is boilerplate though, let's see if we can come up with something better.

**Comment by Tinche** [comment]
Fun fact: the `event_loop` fixture being prepended instead of appended to the list of fixtures for asyncio tests was added recently in https://github.com/pytest-dev/pytest-asyncio/issues/154.

**Comment by Tinche** [comment]
The solution I'm leaning towards is making `event_loop_policy` a magical fixture you should override if you want to install your own policy, like `event_loop` is a magical fixture.

**Comment by alblasco** [comment]
> Apologies for reformatting noise, I'm using black now.

I use black too (and prospector)


> The solution I'm leaning towards is making `event_loop_policy` a magical fixture you should override if you want to install your own policy, like `event_loop` is a magical fixture.

This sounds good. What about the following, as an easy solution :
* Option 1: Only one fixture. You have to include inside event_loop:
```
@pytest.fixture
def event_loop():
    """Create an instance of the default event loop for each test case."""
    asyncio.set_event_loop_policy(XXXLoopPolicy())
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()
    asyncio.set_event_loop_policy(None)
```
* Option 2: Two fixtures (in very special cases, if any, as normally it wouldn´t be needed). And then users have to make explicit dependencies:
```
@pytest.fixture
def event_loop_policy():
    """Create an instance of the default event loop for each test case."""
    asyncio.set_event_loop_policy(XXXLoopPolicy())
    yield loop
    asyncio.set_event_loop_policy(None)

@pytest.fixture
def event_loop(event_loop_policy):
    """Create an instance of the default event loop for each test case."""
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()
```
Or do you want to request a mandatory event_loop_policy fixture?. This could be more disruptive.

**Comment by Tinche** [comment]
Hm actually the suggestion of having users override the policy in the loop fixture is simpler, but less obvious. That might be the way to go if we document it properly. Ideally you wouldn't need to override the policy, overriding the loop would be enough (although you might need to override the policy if the code you're testing deals with it directly).

**Comment by alblasco** [comment]
So I understand that option 2 is the way to go. Fine, it sounds good to me.
Let me know if I can help in anyway.

**Comment by Tinche** [comment]
@alblasco Actually I was going for 1.a. Seems the simplest, we just need to document it.

**Comment by alblasco** [comment]
> @alblasco Actually I was going for 1.a. Seems the simplest, we just need to document it.

Python ZEN: Simple is better than complex.

**Comment by seifertm** [comment]
@Tinche `pytest-asyncio` no longer resets the current policy when creating a new event loop. That means users could set loop policies using regular pytest fixtures.

Can you think of another use case covered by this PR? Is this something we want to pursue?

**Comment by asvetlov** [comment]
Agree with @seifertm

**Comment by Tinche** [comment]
@seifertm agreed! thanks

**Pull request closed without merging**
