### PR TITLE
Derive project version using importlib

### LINKED ISSUE #628: Derive project version in docs from Git Tags
The project version specified in `docs/source/conf.py` has not been bumped since v0.20.1.

The `release` field should be derived automatically from the version determined by setuptools_scm, so there's no need to adjust the version manually upon creating a release.

### PR DESCRIPTION
**Pull request by ka28kumar**
Fixes #628 

Using `importlib` to populate the version field in `conf.py`

### CODE REVIEW

**Review by seifertm — CHANGES_REQUESTED** [review]
The doc build in the CI fails with the error `importlib.metadata.PackageNotFoundError: No package metadata was found for pytest-asyncio`. Probably because pytest-asyncio isn't installed in the Python environment used to build the docs.

You could try adding it to the installed packages in `.readthedocs.yaml` and see if it fixes the issue.
```yaml
python:
  install:
    - path: .
…
```

**Comment by ka28kumar** [comment]
Updated `.readthedocs.yaml`.
On a side note, is there a way to validate something like this locally?
I have little experience with ReadTheDocs and I couldn't find anything on this.

**Comment by seifertm** [comment]
> Updated `.readthedocs.yaml`. On a side note, is there a way to validate something like this locally? I have little experience with ReadTheDocs and I couldn't find anything on this.

You're raising a very good point. It's desirable that the process for building the docs in the CI is the same as locally.
At the moment, this is not the case, though. I'll create an issue for that.

**Comment by seifertm** [comment]
Created #917 to track the build issue.

**Review by seifertm — APPROVED** [review]

**Pull request merged**
