### PR TITLE
trollius support

### PR DESCRIPTION
**Pull request by chassing**
use trollius instead asyncio for python 2

### CODE REVIEW

**Comment by Tinche** [comment]
I'm not really sold on the idea of supporting Trollius/Python 2 in pytest-asyncio. Is this something you personally need?

**Comment by chassing** [comment]
yes indeed. I've a project which supports python 2 and 3 with trollius and asyncio

**Comment by chassing** [comment]
any news about it?

**Comment by Tinche** [comment]
I've thought about it, but since the Trollius project is now deprecated (http://trollius.readthedocs.org/deprecated.html#deprecated), I don't think it's worth it. Sorry.

**Pull request closed without merging**
