### PR TITLE
plugin: Use pytest 5.4.0 new Function API

### PR DESCRIPTION
**Pull request by romainletendart**
This fixes https://github.com/pytest-dev/pytest-asyncio/issues/141.

### CODE REVIEW

**Comment by mjpieters** [comment]
This change means this project can only work with Pytest 5.4.0 and up. Either

- Update the install_requires metadata to reflect this dependency
- Allow for a fallback, perhaps with a `try: ... except AttributeError:` block, to calling `pytest.Function()` directly again.

**Comment by romainletendart** [comment]
@mjpieters Thank you for your review.
I have updated `install_requires` accordingly.

**Comment by simonfagerholm** [comment]
@romainletendart: The reason this PR fails has been fixed in #148, just waiting for review (maybe @mjpieters has the time to check?) and merge.
This branch will probably need to pull in the master branch when that happens, as the changes are needed and that my commit also changed the install_requires, but to only work with pytest < 5.4.0.

**Comment by dmitrypolo** [comment]
@simonfagerholm wouldn't it be better to follow @mjpieters advice and instead of constraining users from using newer versions of `pytest` to have a fallback to call `pytest.Function()` based on the version?

**Comment by simonfagerholm** [comment]
@dmitrypolo maybe you meant  to message @romainletendart?

**Comment by dmitrypolo** [comment]
@simonfagerholm  @romainletendart my comment applies to both of you technically. This PR confines users from using `pytest < 5.4` whereas yours confines users from using `pytest > 5.4`.

**Comment by simonfagerholm** [comment]
@dmitrypolo Before this PR is merged pytest 5.4.0 and above is not supported. To be able to use pytest >= 5.4.0 this PR is needed. My PR correctly reflects that only pytest < 5.4.0 is supported

**Comment by dmitrypolo** [comment]
@simonfagerholm correct, I guess the point I am trying to get across is we should probably try to allow for both users of `pytest < 5.4` and `pytest > 5.4` to use this plug-in. The issue is that both of these PRs restrict users in one-way or the other.

**Comment by simonfagerholm** [comment]
@dmitrypolo Yes but in my case its for good reason: It isn't compatible... I can understand that you would like it to be backwards compatible, but that is only with this PR and not mine.

**Comment by romainletendart** [comment]
> @simonfagerholm wouldn't it be better to follow @mjpieters advice and instead of constraining users from using newer versions of `pytest` to have a fallback to call `pytest.Function()` based on the version?

I'm not sure supporting multiple API versions inside the code itself is a good idea.
Just suppose you do this for every API change and your code quickly becomes unreadable because of all the ifs you added to support multiple versions.
Plus, you get high chances to get corner case bugs with some weird combinations of versions that were not supposed to work together initially.

@simonfagerholm, I will definitely rebase on the upstream master once your merged your PR just to be sure everything is green before being able to merge my own PR.

**Comment by simonfagerholm** [comment]
@romainletendart I totally agree.
I'll let you know when its merged. Just need someone with write access to review and approve.

**Comment by romainletendart** [comment]
Maybe we could ask @Tinche as he seems to be both the initiator and the main contributor of pytest-asyncio?

**Comment by Tinche** [comment]
@romainletendart Fix the merge conflict please and let's get this in!

**Comment by simonfagerholm** [comment]
@romainletendart Like @Tinche said: my PR is in, pull it and lets get this in! :)

**Comment by romainletendart** [comment]
@Tinche @simonfagerholm Merge conflict fixed, thank you! :)

**Comment by simonfagerholm** [comment]
@Tinche Seems good to go! :)

**Comment by Tinche** [comment]
Thank you kindly!

**Pull request merged**
